#!/bin/bash
# Script name: /etc/pm/sleep.d/1000trackpoint
# Purpose: Reset the Trackpoint after resuming from sleep
# Edit the variables below to configure the Trackpoint
speed=120
sensitivity=250

if [ "$1" = "resume" ]
then
    echo -n $speed > /sys/devices/platform/i8042/serio1/serio2/speed
    echo -n $sensitivity > /sys/devices/platform/i8042/serio1/serio2/sensitivity
fi
